# Site settings
title: "Zafaryab Haider"                    # Change this to your full name or "Portfolio of [Your Name]"
description: "Engineer and Photographer"  # A brief description of what you do
logo: /assets/img/logo.png             # Add a logo image here if you want, otherwise remove this line

# Social and Analytics
google_analytics: UA-XXXXXXXX-X        # Replace with your Google Analytics ID if you have one

# Theme settings
theme: jekyll-theme-minimal
show_downloads: false                  # Set to false unless you specifically want people to download the theme files

# URL settings
baseurl: ""                            # Leave blank for user.github.io
url: "https://yourusername.github.io"  # Replace with your GitHub Pages URL

# Custom Navigation Links
# Adding navigation links to your pages (Resume, Projects, Photography)
header_pages:
  - index.md
  - resume.md
  - projects.md
  - photography.md

# Optional social links
# Add links to your social media profiles or GitHub
social_links:
  twitter: your_twitter_username
  github: your_github_username
  linkedin: your_linkedin_username
  instagram: your_instagram_username    # Useful if you want to showcase your photography on Instagram

# Footer settings
footer:
  copyright: "&copy; 2024 [Your Name]"   # Replace with the current year and your name
  powered_by: "Jekyll and GitHub Pages" # Optional; you can remove or edit this as you wish

# Markdown Options
markdown: kramdown

# Permalink Settings (Optional)
permalink: pretty                       # Makes URLs more readable, like /resume/ instead of /resume.html

# Plugins (for additional features if needed)
plugins:
  - jekyll-seo-tag                      # Adds SEO tags to your site for better search engine visibility
  - jekyll-sitemap                      # Generates a sitemap for search engines
  - jekyll-feed                         # Generates an RSS feed
